<?php
$this->title="Tic-Tac-Toe game";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Back</a></p>
<head>
    <link href="/game/css/main.8a935685.chunk.css" rel="stylesheet">
</head>
<body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <script src="/game/js/runtime~main.a8a9905a.js"></script>
    <script src="/game/js/2.0e3f6a1a.chunk.js"></script>
    <script src="/game/js/main.972f40ac.chunk.js"></script>
</body>
