<?php
$this->title = '老婆大人你快来试试我的新成果';
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'game')); ?>">Tic-Tac-Toe game</a></p>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'blog')); ?>">Blog Module</a></p>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'restc')); ?>">Rest Module</a></p>
<p><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'add')); ?>">Add new album</a></p>
<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->albums as $album) : ?>
    <tr>
        <td><?php echo $this->escape($album->title); ?></td>
        <td><?php echo $this->escape($album->artist); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'edit', 'id' => $album->id)); ?>">Edit</a>
            <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'delete', 'id' => $album->id)); ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
